---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: gomod
    directory: "/lambda"
    schedule:
      interval: "monthly"
  - package-ecosystem: terraform
    directory: "/infrastructure"
    schedule:
      interval: "monthly"