name: Automating build, tests and lambda packaging for Golang 

on:
  push:
    branches: [ "main" ]
  pull_request:
    
jobs:
  build:
    if: ! startsWith(github.head_ref, 'refs/heads/iac/')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.1'

    - name: Build
      run: go build -C lambda -o build/go-serverless -v

    # - name: Test
    #   run: go test -v lambda/...

    # this step will be done on the IaC level
    # - name: Zipping executable
    #   run: zip -jrm lambda/build/go-serverless.zip lambda/build/go-serverless